:doctype: book
:toc: macro
:toclevels: 4
:sectnumlevels: 6
:numbered:
:chapter-label:
:icons: font

= OpenShift 4 KVM UPI

Terraform first approach to install an OpenShift 4 cluster under KVM / libvirt and HAProxy as the load balancer.

Notable highlights of this approach:

* <<Cluster Installation Configuration Generation>>
* <<Dynamic Inventory Generation>>
* <<MAC Address Generation for Nodes>>
* <<Terraform JSON Ingestion as Variables>>
* <<libvirt Network Namespaces>>
* <<Load Balancer Provisioning>>

toc::[]


== Usage


=== Prerequisites

* Install libvirt:
** https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/[Fedora]
** https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_and_managing_virtualization/getting-started-with-virtualization-in-rhel-8_configuring-and-managing-virtualization[RHEL 8]
** https://wiki.libvirt.org/page/UbuntuKVMWalkthrough[Ubuntu and Pop!OS]
* https://learn.hashicorp.com/tutorials/terraform/install-cli[Install Terraform]
* https://github.com/dmacvicar/terraform-provider-libvirt#installing[Install libvirt Provider]
* https://cloud.centos.org/centos/8/x86_64/images/[CentOS 8 Generic Cloud Image (for load balancer node)]
* http://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/[OpenShift QEMU Image]
* OpenShift Installer
* Pull Secret
* https://www.ansible.com/[Ansible]


=== Tested Configurations

* Pop!OS 20.04 LTS
* OpenShift 4.5.14
* Terraform v0.12


=== Add libvirt dnsmasq server to Network Manager

* In `/etc/NetworkManager/dnsmasq.d/` create a file for the DNS configuration. This will allow the host system to resolve addresses for the cluster using the libvirt DNS mask instance listening on the specified IP address. For example, we might use:
[source,bash]
----
cat <<EOF > sudo /etc/NetworkManager/dnsmasq.d/ocp.dnsmasq.conf
server=/ocp.example.io/192.168.200.1
EOF
----

* In `/etc/NetworkManager/conf.d/` create a file to instruct Network Manager to consult dnsmasq for DNS resolutions:

[source,bash]
----
cat <<EOF > sudo /etc/NetworkMnager/conf.d/nm.global.conf
[main]
dns=dnsmasq
EOF
----

* Restart Network Manager:
[source,bash]
----
sudo systemctl restart NetworkManager
----


=== Override Terraform Variables for OpenShift Installer and Pull Secret

In `terraform.tfvars`:
[source,hcl]
----
openshift_installer = "<path-to-openshift-installer>"
pull_secret_file    = "<path-to-pull-secret-file>"
----

[NOTE]
====
Paths may be absolute or relative.
====


=== Override Terraform Variables for OpenShift Cluster Nodes

For now, consult `variables.tf`.

*TODO* This will be updated later to provide more comphrensive configuration guidance.


=== Install

[source,bash]
----
terraform init
terraform plan
terraform apply -auto-approve
----

HAProxy statistics page is enabled and you can reach it via: http://loadbalancer.<cluster-name>.<base-domain-name>:8404/stats


=== Uninstall

[source, bash]
----
terraform destroy -auto-approve
----


== Details


=== Cluster Installation Configuration Generation

*TODO*

We automatically generate the `install-config.yaml` for the cluster, generate cluster SSH key pair and SSH key pair
for load balancer node.


=== Dynamic Inventory Generation

*TODO*

We dynamically generate the infrastructure inventory data that will be used to provision the infrastructure.


=== MAC Address Generation for Nodes

*TODO*

We use a procedural based approach when generating the MAC addresses for the nodes. This is used to
setup DHCP reservations in on the libvirt network for every node. Doing this assures that we know what they are ahead of
time instead of having to come back and query libvirt for the IP address assigned to each node while the infrastructure
is being provisioned.


=== Terraform JSON Ingestion as Variables

*TODO*

We leverage Terraform's ability to ingest JSON and use it as a source of variables. We exploit this to generate the
necessary cluster node assets prior to provisioning them.


=== libvirt Network Namespaces

*TODO*

We take advantage of https://libvirt.org/formatnetwork.html#elementsNamespaces[libvirt Network Namespaces] to set up
wildcard DNS for default ingress so you don't have to.


=== Load Balancer Provisioning

*TODO*

A dedicated node is automatically provisioned for the HAProxy node.


== Acknowledgements

* David Dreggors, Red Hat
** For the idea, inspiration and discussion of <<MAC Address Generation for Nodes>>
** A very nice, working and sustainable HAProxy configuration
